server:
  port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

security:
  private_key_path: "keys/private.pem"
  public_key_path: "keys/public.pem"
  key_size: 2048

issuers:
  - id: "keycloak-local"
    issuer: "http://localhost:8080/realms/mcp-realm"
    jwks_endpoint: "http://localhost:8080/realms/mcp-realm/protocol/openid-connect/certs"
    audience: "agent-sts"
  
  - id: "agent-sts"
    issuer: "agent-sts"
    jwks_endpoint: "http://localhost:8081/.well-known/jwks.json"
    audience: "agent-sts"

claims:
  persistent:
    - from: "sub"
      to: "sub"
      required: true
      description: "Original subject"
    
    - from: "may_act"
      to: "may_act"
      required: false
      description: "Authorization delegation permissions"

    - from: "name"
      to: "name"
      required: false            
  
  transient:
    - from: "email"
      to: "email"
      required: false
    
    - from: "groups"
      to: "groups"
      required: false

    - from: "preferred_username"
      to: "name"
      required: false                  
    


actor:
  max_chain_depth: 5
  metadata_endpoint: "http://169.254.169.111/connection"
  default_audience: ""
