# yaml-language-server: $schema=../../schema/local.json
config:
  tracing:
    otlpEndpoint: http://localhost:4317
    randomSampling: true
  logging:
    fields:
      add:
        # Add JWT actor claim
        "jwt.act": "jwt.act"    
binds:
- port: 3000
  listeners:
  - hostname: "supply-chain-agent.localhost"
    routes:
    - policies:
        # Mark this route as a2a traffic
        a2a: {}
        jwtAuth:
          mode: strict
          issuer: agent-sts
          audiences: [supply-chain-agent]
          jwks:
            url: http://localhost:8081/.well-known/jwks.json        
        backendAuth:
          passthrough: {}
        authorization:
          rules:
          - 'jwt.name == "mcp-user"'
        cors:
          allowOrigins:
            - "*"
          allowHeaders:
            - "*"
      backends:
      - host: localhost:9999

  - hostname: "market-analysis-agent.localhost"
    routes:
    - policies:
        # Mark this route as a2a traffic
        a2a: {}
        jwtAuth:
          mode: strict
          issuer: agent-sts
          audiences: [supply-chain-agent]
          jwks:
            url: http://localhost:8081/.well-known/jwks.json            
        cors:
          allowOrigins:
            - "*"
          allowHeaders:
            - "*"
      backends:
      - host: localhost:9998      

  - routes:
    - name: general-mcp
      matches:
      - path:
          pathPrefix: /general/mcp
      policies:
        cors:
          allowOrigins:
            - "*"
          allowHeaders:
            - "*"
        jwtAuth:
          mode: strict
          issuer: agent-sts
          audiences: [supply-chain-agent]
          jwks:
            url: http://localhost:8081/.well-known/jwks.json         
      backends:
      - mcp:
          targets:
          - name: time
            stdio:
              cmd: uvx
              args: ["mcp-server-time"]
          - name: everything
            stdio:
              cmd: npx
              args: ["@modelcontextprotocol/server-everything"]
          - name: mcp-sequential-thinking
            stdio:
              cmd: npx
              args: ["@modelcontextprotocol/server-sequential-thinking"]              
    

